//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VegetableTracker.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VegetableTracker.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VegetableTracker.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeTab {
            get {
                return ResourceManager.GetString("HomeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The American Gut Project examined stool samples from over 10,000 people worldwide and found that participants who ate more than 30 different plant-based foods per week had a significantly more diverse gut microbiome than those who consumed only ten different plants. science.ORF.at
        ///
        ///Each plant provides unique fiber and secondary plant compounds — food for different bacterial strains in your gut. The more colorful your plate, the better your gut flora.
        ///
        ///This app helps you track your plant diversity per we [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IntroText {
            get {
                return ResourceManager.GetString("IntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 Days.
        /// </summary>
        public static string Last7Days {
            get {
                return ResourceManager.GetString("Last7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} vegetables.
        /// </summary>
        public static string ProgressFormat {
            get {
                return ResourceManager.GetString("ProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search vegetables....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Details.
        /// </summary>
        public static string SeeDetails {
            get {
                return ResourceManager.GetString("SeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 Days — Details.
        /// </summary>
        public static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add custom vegetable.
        /// </summary>
        public static string AddCustomVegetable {
            get {
                return ResourceManager.GetString("AddCustomVegetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter vegetable name.
        /// </summary>
        public static string EnterVegetableName {
            get {
                return ResourceManager.GetString("EnterVegetableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vegetable with this name already exists..
        /// </summary>
        public static string VegetableAlreadyExists {
            get {
                return ResourceManager.GetString("VegetableAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Suggestions.
        /// </summary>
        public static string ShowSuggestions {
            get {
                return ResourceManager.GetString("ShowSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        public static string SuggestionsTitle {
            get {
                return ResourceManager.GetString("SuggestionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Vegetable.
        /// </summary>
        public static string SelectVegetableTitle {
            get {
                return ResourceManager.GetString("SelectVegetableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artichoke.
        /// </summary>
        public static string Vegetable_artichoke {
            get {
                return ResourceManager.GetString("Vegetable_artichoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arugula.
        /// </summary>
        public static string Vegetable_arugula {
            get {
                return ResourceManager.GetString("Vegetable_arugula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asparagus.
        /// </summary>
        public static string Vegetable_asparagus {
            get {
                return ResourceManager.GetString("Vegetable_asparagus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bamboo Shoots.
        /// </summary>
        public static string Vegetable_bamboo_shoots {
            get {
                return ResourceManager.GetString("Vegetable_bamboo_shoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bean Sprouts.
        /// </summary>
        public static string Vegetable_bean_sprouts {
            get {
                return ResourceManager.GetString("Vegetable_bean_sprouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beet.
        /// </summary>
        public static string Vegetable_beet {
            get {
                return ResourceManager.GetString("Vegetable_beet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bell Pepper.
        /// </summary>
        public static string Vegetable_bell_pepper {
            get {
                return ResourceManager.GetString("Vegetable_bell_pepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bok Choy.
        /// </summary>
        public static string Vegetable_bok_choy {
            get {
                return ResourceManager.GetString("Vegetable_bok_choy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broccoli.
        /// </summary>
        public static string Vegetable_broccoli {
            get {
                return ResourceManager.GetString("Vegetable_broccoli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brussels Sprouts.
        /// </summary>
        public static string Vegetable_brussels_sprouts {
            get {
                return ResourceManager.GetString("Vegetable_brussels_sprouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butternut Squash.
        /// </summary>
        public static string Vegetable_butternut_squash {
            get {
                return ResourceManager.GetString("Vegetable_butternut_squash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabbage.
        /// </summary>
        public static string Vegetable_cabbage {
            get {
                return ResourceManager.GetString("Vegetable_cabbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrot.
        /// </summary>
        public static string Vegetable_carrot {
            get {
                return ResourceManager.GetString("Vegetable_carrot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cauliflower.
        /// </summary>
        public static string Vegetable_cauliflower {
            get {
                return ResourceManager.GetString("Vegetable_cauliflower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celeriac.
        /// </summary>
        public static string Vegetable_celeriac {
            get {
                return ResourceManager.GetString("Vegetable_celeriac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celery.
        /// </summary>
        public static string Vegetable_celery {
            get {
                return ResourceManager.GetString("Vegetable_celery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chard.
        /// </summary>
        public static string Vegetable_chard {
            get {
                return ResourceManager.GetString("Vegetable_chard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chayote.
        /// </summary>
        public static string Vegetable_chayote {
            get {
                return ResourceManager.GetString("Vegetable_chayote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collard Greens.
        /// </summary>
        public static string Vegetable_collard_greens {
            get {
                return ResourceManager.GetString("Vegetable_collard_greens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corn.
        /// </summary>
        public static string Vegetable_corn {
            get {
                return ResourceManager.GetString("Vegetable_corn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cucumber.
        /// </summary>
        public static string Vegetable_cucumber {
            get {
                return ResourceManager.GetString("Vegetable_cucumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daikon.
        /// </summary>
        public static string Vegetable_daikon {
            get {
                return ResourceManager.GetString("Vegetable_daikon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eggplant.
        /// </summary>
        public static string Vegetable_eggplant {
            get {
                return ResourceManager.GetString("Vegetable_eggplant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endive.
        /// </summary>
        public static string Vegetable_endive {
            get {
                return ResourceManager.GetString("Vegetable_endive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fennel.
        /// </summary>
        public static string Vegetable_fennel {
            get {
                return ResourceManager.GetString("Vegetable_fennel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garlic.
        /// </summary>
        public static string Vegetable_garlic {
            get {
                return ResourceManager.GetString("Vegetable_garlic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Beans.
        /// </summary>
        public static string Vegetable_green_beans {
            get {
                return ResourceManager.GetString("Vegetable_green_beans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jicama.
        /// </summary>
        public static string Vegetable_jicama {
            get {
                return ResourceManager.GetString("Vegetable_jicama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kale.
        /// </summary>
        public static string Vegetable_kale {
            get {
                return ResourceManager.GetString("Vegetable_kale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kohlrabi.
        /// </summary>
        public static string Vegetable_kohlrabi {
            get {
                return ResourceManager.GetString("Vegetable_kohlrabi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leek.
        /// </summary>
        public static string Vegetable_leek {
            get {
                return ResourceManager.GetString("Vegetable_leek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lettuce.
        /// </summary>
        public static string Vegetable_lettuce {
            get {
                return ResourceManager.GetString("Vegetable_lettuce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mushroom.
        /// </summary>
        public static string Vegetable_mushroom {
            get {
                return ResourceManager.GetString("Vegetable_mushroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okra.
        /// </summary>
        public static string Vegetable_okra {
            get {
                return ResourceManager.GetString("Vegetable_okra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onion.
        /// </summary>
        public static string Vegetable_onion {
            get {
                return ResourceManager.GetString("Vegetable_onion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsnip.
        /// </summary>
        public static string Vegetable_parsnip {
            get {
                return ResourceManager.GetString("Vegetable_parsnip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peas.
        /// </summary>
        public static string Vegetable_peas {
            get {
                return ResourceManager.GetString("Vegetable_peas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potato.
        /// </summary>
        public static string Vegetable_potato {
            get {
                return ResourceManager.GetString("Vegetable_potato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumpkin.
        /// </summary>
        public static string Vegetable_pumpkin {
            get {
                return ResourceManager.GetString("Vegetable_pumpkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radicchio.
        /// </summary>
        public static string Vegetable_radicchio {
            get {
                return ResourceManager.GetString("Vegetable_radicchio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radish.
        /// </summary>
        public static string Vegetable_radish {
            get {
                return ResourceManager.GetString("Vegetable_radish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rutabaga.
        /// </summary>
        public static string Vegetable_rutabaga {
            get {
                return ResourceManager.GetString("Vegetable_rutabaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shallot.
        /// </summary>
        public static string Vegetable_shallot {
            get {
                return ResourceManager.GetString("Vegetable_shallot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap Peas.
        /// </summary>
        public static string Vegetable_snap_peas {
            get {
                return ResourceManager.GetString("Vegetable_snap_peas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spinach.
        /// </summary>
        public static string Vegetable_spinach {
            get {
                return ResourceManager.GetString("Vegetable_spinach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweet Potato.
        /// </summary>
        public static string Vegetable_sweet_potato {
            get {
                return ResourceManager.GetString("Vegetable_sweet_potato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomato.
        /// </summary>
        public static string Vegetable_tomato {
            get {
                return ResourceManager.GetString("Vegetable_tomato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnip.
        /// </summary>
        public static string Vegetable_turnip {
            get {
                return ResourceManager.GetString("Vegetable_turnip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watercress.
        /// </summary>
        public static string Vegetable_watercress {
            get {
                return ResourceManager.GetString("Vegetable_watercress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zucchini.
        /// </summary>
        public static string Vegetable_zucchini {
            get {
                return ResourceManager.GetString("Vegetable_zucchini", resourceCulture);
            }
        }
    }
}
